package common

const (
	REQ_USER_KEY          = "user"
	NETWORK_SCENARIO_TYPE = "NETWORK"
	PROXY_SCENARIO_TYPE   = "PROXY"
	HTTP_SCENARIO_TYPE    = "HTTP_RESPONSE"
	ISO_DATE_FORMAT       = "2022-07-30T21:03:09+00:00"
)
